# Generated by Django 3.0.1 on 2021-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.TextField(max_length=300)),
                ('buyer_mobile', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=120, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=120, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('mobile_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=50)),
                ('mob_image', models.ImageField(upload_to='images')),
                ('specification', models.TextField(max_length=200)),
            ],
        ),
    ]
