# Generated by Django 3.0.1 on 2021-03-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('NO', 'NewOrder'), ('P', 'Packing'), ('D', 'Dispatch'), ('CD', 'Complete Deleivery')], max_length=2, null=True),
        ),
    ]
